### ISSUE TITLE
Streamlit Doesn't Provide Text!

### ISSUE THREAD

**Issue by ModestMC** [jojo96/ASCIIGan#1]
This is honestly a pretty cool project, I was thinking a GAN would be the way to do it and of course somebody did. Nicely done!

As far as improving the code, I have nothing useful to say right this second; however, the Streamlet is a great way to try before you buy (into downloading and running the thing).

I ran the following image through, was genuinely impressed, but there's no way to get the actual ASCII!
Obviously there are challenges with formatting and color and whatnot (maybe even character set?) but my hunch is this was simply an oversight. I'd love to take the text I got out of the thing and show it to some friends. Stay great!

![image](https://user-images.githubusercontent.com/45748401/195778490-e6a0ed8a-0944-4287-a8e3-47d327b5656a.png)

**Comment by jojo96** [comment]
> This is honestly a pretty cool project, I was thinking a GAN would be the way to do it and of course somebody did. Nicely done!
> 
> As far as improving the code, I have nothing useful to say right this second; however, the Streamlet is a great way to try before you buy (into downloading and running the thing).
> 
> I ran the following image through, was genuinely impressed, but there's no way to get the actual ASCII! Obviously there are challenges with formatting and color and whatnot (maybe even character set?) but my hunch is this was simply an oversight. I'd love to take the text I got out of the thing and show it to some friends. Stay great!
> 
> ![image](https://user-images.githubusercontent.com/45748401/195778490-e6a0ed8a-0944-4287-a8e3-47d327b5656a.png)

Hey. Thank you for the nice words :) Definitely, a nice idea to include the ASCII too. Maybe pytesseract ocr could be useful. Feel free to contribute or add features :)
